### ISSUE TITLE
Example of classes  EntityTypeConfiguration and ComplexTypeConfiguration

### ISSUE THREAD

**Issue by leolana** [eduardosilva/entity-framework-guide#2]
In OnModelCreating method where you explain how to load the settings and the conventions of EF automatically uses two EntityTypeConfiguration and ComplexTypeConfiguration classes that are not in the rest of his examples. How would be the structure of these classes is possible to insert one piece as an example?

**Comment by eduardosilva** [comment]
[EntityTypeConfiguration](https://msdn.microsoft.com/en-us/library/gg696117%28v=vs.113%29.aspx and)  and [ComplexTypeConfiguration](https://msdn.microsoft.com/en-us/library/gg696149%28v=vs.113%29.aspx) are Entity Framework classes.
